role_name        = "prod_s3_role"
iam_policy       = "prod_s3_role_policy"
ami              = "ami-02bf8ce06a8ed6092"
instance_type    = "t2.micro"
instance_name    = "terraform_prod_instance"
key_name         = "k8-key"
avzone           = "us-east-2a"